exports.fakeTitle = [
  'Cozy cabin',
  'Refuberished House',
  'Stylish Features, LEED Certified',
  'Come live in our luxury rooms!',
  'First Floor Triplex.',
  'Private Patio - Close to nothing!',
  'Large bright walk up~Upgraded finishes~',
  'Walking distance to Starbucks, Sprouts',
  'Quartz countertops, Guest parking',
  'Bright, quiet house for rent',
  'Lovely fresh lower duplex',
  'Luxury Home',
  ' @@*GREAT LOCATION*@@ BOOK NOW',
  'This Three Bedroom Has Everything You Need',
  ' Remarkable Value! Unbeatable Location! ',
  'MODERN AND CLASSY HOME',
  'My Home',
  'Brick Home',
  'Luxury Treehouse',
  'Lovely cabin',
  'Not so haunted mansion',
  'Re-outfitted home in great location',
  'Middle of no where home. Modern look',
  'Adorable cottage',
  'SPACIOUS home in suburbs',
  'Townhouse lots of Steps Away from everything',
  'Stunning rebulit home! John wick stayed here.',
  'Luxury Home. can be urs',
  'CHEAP housing outfitted with desk',
  'REMODELED HOME',
  'Rundown church rebulit to home',
  'In the middle of no where home',
  'Voted most boringest place',
  'Nothing ever happens at this house',
  'A home with TV with only CNN',
  'Wifi-less area, very little signal, mansion',
  'Cat mansion. Theres cats everywhere',
  'Home close to grocery stores . Small area',
  'Smart home in remote location',
  'Great place for a secret meeting',
  'Lose your mind in boredom at this house',
  'Great views at small home',
  'The GREAT PALACE',
  ' Excellence in boredom. West Manor',
  'no pets. Rundown shack',
  'Nothing near here. Big home',
  'This place is like the moon. empty.',
  'Boredom to a new level! Big home!',
  'Home at mostly empty neighborhood.',
  'Great historical spot. Bird manor.'
]
